<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datesTable</name>
   <tag></tag>
   <elementGuidId>3378eb5a-92ec-4447-8edf-8e241357ea0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='managementKioskview']//div[2]//div[1]//div[4]//div[1]//div[2]//table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
