<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>driverTciketView</name>
   <tag></tag>
   <elementGuidId>bff75222-ec2e-4fc6-8b20-3824e0102aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#managementKioskview</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
