<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>preSalaryTab</name>
   <tag></tag>
   <elementGuidId>4ca32807-4037-443f-92cb-4e4f0a4df5e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preSalaryview</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
