<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gridLoadingBar</name>
   <tag></tag>
   <elementGuidId>a26fd608-5a30-4bf0-b41c-189ad45e7e85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.k-loading-mask:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
