<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainEmptyBackground</name>
   <tag></tag>
   <elementGuidId>3b8397cc-6296-48df-b205-c2ebcbaec0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empty-cards-background</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
