<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>safetyOfficer</name>
   <tag></tag>
   <elementGuidId>11767b04-47e0-481c-b318-36385a8db0ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id=&quot;8ea1a6ac-ca71-4cb4-bf7f-370bf6a818cd&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
