<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rightSideTable</name>
   <tag></tag>
   <elementGuidId>b06d9ed0-ee9d-46c1-a329-c70b8c05d3bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preSalaryDetailsgrid</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
