<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>taskTrackingView</name>
   <tag></tag>
   <elementGuidId>91458a32-a43e-4ec6-b4fa-a4b18b1e3e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[id*=&quot;taskTracking&quot;]:not([id*=&quot;Panel&quot;])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
