<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first Name</name>
   <tag></tag>
   <elementGuidId>b206c065-af8f-4a7a-9c27-810351e9f8d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>30</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-28 ng-dirty ng-valid-parse ng-touched ng-empty ng-invalid ng-invalid-required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>שדה חובה</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.model.person.firstName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>originalXpath</name>
      <type>Main</type>
      <value>id(&quot;employee0104369b-b540-4b12-7f9a-96a8bb4e9bd2view&quot;)/div[@class=&quot;flx-aut flx-on flx-clmn ng-scope&quot;]/div[@class=&quot;flx-aut flx-on flx-clmn ng-scope&quot;]/div[@class=&quot;row x-no-mrg-pad x-margin01 flx-on flx-aut ng-scope&quot;]/ng-form[@class=&quot;col-xs-10 flx-on flx-clmn flx-aut x-no-pad-right x-no-pad-left ng-invalid ng-invalid-required ng-valid-email ng-valid-pattern ng-dirty ng-valid-parse&quot;]/div[@class=&quot;tab-content-inner flx-on flx-clmn flx-aut ng-scope&quot;]/ng-form[@class=&quot;flx-aut flx-on flx-clmn x-content-3 ovr-auto x-no-mrg-pad re-gutter pad-20 ng-scope ng-invalid ng-invalid-required ng-valid-email ng-dirty ng-valid-parse&quot;]/div[@class=&quot;flx-aut row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;row no-gutter&quot;]/div[@class=&quot;col-sm-8 col-lg-9&quot;]/input[@class=&quot;form-control input-28 ng-dirty ng-valid-parse ng-touched ng-empty ng-invalid ng-invalid-required&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//input[@type='text'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='employee0104369b-b540-4b12-7f9a-96a8bb4e9bd2view']/div/div/div[3]/ng-form/div/ng-form/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='שם פרטי'])[2]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='פעיל'])[1]/following::input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='שם משפחה'])[2]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='כינוי'])[2]/preceding::input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//ng-form/div/div/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
